export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const CREATE_RESTAURANT = 'CREATE_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const SELECT_RESTAURANT = 'SELECT_RESTAURANT';
export const UPLOAD_RESTAURANT_IMAGE = 'UPLOAD_RESTAURANT_IMAGE';

export const SHOW_RESTAURANT_FORM = 'SHOW_RESTAURANT_FORM'; 
export const HIDE_RESTAURANT_FORM = 'HIDE_RESTAURANT_FORM'; 

export const GET_MENUITEMS = 'GET_MENUITEMS';
export const CREATE_MENUITEM = 'CREATE_MENUITEM';
export const DELETE_MENUITEM = 'DELETE_MENUITEM';
export const UPLOAD_MENUITEM_MEDIA = 'UPLOAD_MENUITEM_MEDIA';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';