export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const CREATE_RESTAURANT = 'CREATE_RESTAURANT';
export const SELECT_RESTAURANT = 'SELECT_RESTAURANT';

export const SHOW_RESTAURANT_FORM = 'SHOW_RESTAURANT_FORM'; 
export const HIDE_RESTAURANT_FORM = 'HIDE_RESTAURANT_FORM'; 